all:
  hosts:
    controller:
      ansible_host: 192.168.58.20
      ip: 192.168.58.20
      access_ip: 192.168.58.20
    node1:
      ansible_host: 192.168.58.21
      ip: 192.168.58.21
      access_ip: 192.168.58.21
    node2:
      ansible_host: 192.168.58.22
      ip: 192.168.58.22
      access_ip: 192.168.58.22
  children:
    kube_control_plane:
      hosts:
        controller:
    kube_node:
      hosts:
        controller:
        node1:
        node2:
    etcd:
      hosts:
        controller:
        node1:
        node2:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
